import { defineConfig } from '@terrazzo/cli'
import css from '@terrazzo/plugin-css'

export default defineConfig({
  tokens: ['./holocomm.resolver.json'],
  outDir: './generated',
  plugins: [
    css({
      filename: 'tokens.css',
      variableName: token => `--${token.id.replace(/\./g, '-')}`,
      include: [
        'base.color.black',
        'base.color.white',
        'base.color.neutral.**',
        'base.color.blue.**',
        'base.color.green.3',
        'base.color.green.5',
        'base.color.yellow.2',
        'base.color.yellow.5',
        'base.color.red.3',
        'base.color.red.5',
        'base.color.red.6',
        'base.color.red.7',
        'bgColor.default',
        'bgColor.muted',
        'bgColor.inset',
        'bgColor.disabled',
        'bgColor.accent.emphasis',
        'fgColor.default',
        'fgColor.muted',
        'fgColor.onEmphasis',
        'fgColor.disabled',
        'fgColor.success',
        'fgColor.attention',
        'fgColor.danger',
        'borderColor.default',
        'borderColor.emphasis',
        'borderColor.accent.emphasis',
        'control.bgColor.rest',
        'control.bgColor.hover',
        'color.**',
        'space.**',
        'size.**',
        'font.**',
        'font-size.**',
        'font-weight.**',
        'line-height.**',
        'radius.**',
        'duration.**',
        'ease.**',
        'stroke.**',
        'layout.**',
        'layer.**',
      ],
      permutations: [
        {
          input: { theme: 'dark-dimmed', size: 'default' },
          prepare: contents => `:root {\n  color-scheme: dark;\n  ${contents}\n}`,
        },
        {
          input: { theme: 'light', size: 'default' },
          prepare: contents => `[data-color-scheme='light'] {\n  color-scheme: light;\n  ${contents}\n}`,
        },
      ],
    }),
  ],
  lint: {
    build: { enabled: true },
    rules: {
      'core/valid-color': 'error',
      'core/valid-dimension': 'error',
      'core/valid-duration': 'error',
      'core/valid-cubic-bezier': 'error',
      'core/consistent-naming': 'off',
    },
  },
})
